/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Session { 
    sessionId?: string;
    reference?: string;
    state?: Session.StateEnum;
    startedOnUtc?: Date;
    startDuration?: string;
    maxDurationLimit?: string;
}
export namespace Session {
    export type StateEnum = 'Requested' | 'Delivered' | 'Started' | 'Ended' | 'Canceled' | 'DeliveryTimeout' | 'ResponseTimeout';
    export const StateEnum = {
        Requested: 'Requested' as StateEnum,
        Delivered: 'Delivered' as StateEnum,
        Started: 'Started' as StateEnum,
        Ended: 'Ended' as StateEnum,
        Canceled: 'Canceled' as StateEnum,
        DeliveryTimeout: 'DeliveryTimeout' as StateEnum,
        ResponseTimeout: 'ResponseTimeout' as StateEnum
    };
}
