/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StationSettings { 
    stationId?: string;
    displayName?: string;
    qrCode?: string;
    controlMode?: StationSettings.ControlModeEnum;
}
export namespace StationSettings {
    export type ControlModeEnum = 'Undefined' | 'Local' | 'Remote' | 'RemoteWithQrCode';
    export const ControlModeEnum = {
        Undefined: 'Undefined' as ControlModeEnum,
        Local: 'Local' as ControlModeEnum,
        Remote: 'Remote' as ControlModeEnum,
        RemoteWithQrCode: 'RemoteWithQrCode' as ControlModeEnum
    };
}
